[package]
name = "skim"
version = "0.2.1-beta.2"
authors = ["Mark Wallace <lotabout@gmail.com>"]
description = "Fuzzy Finder in rust!"
documentation = "https://github.com/lotabout/skim"
homepage = "https://github.com/lotabout/skim"
repository = "https://github.com/lotabout/skim"
readme  = "README.md"
keywords = ["fuzzy", "menu", "util"]
license = "MIT"

[[bin]]
name = "sk"

[dependencies]
libc = "0.2.20"
getopts = "0.2"
regex = "0.2"
lazy_static = "0.2.1"
clippy = {version = "0.0.108", optional = true}
shlex = "0.1.1"
utf8parse = "0.1.0"
unicode-width = "0.1.4"
log = "0.3.8"
env_logger = "0.4.3"
time = "0.1.38"

[dependencies.ncurses]
version = "5.85.0"
features = ["wide"]

[features]
default = []

[profile.release]
debug = false
